project:
  type: website
  output-dir: docs

output:
  revealjs:
    self-contained: false

title: "Robust Bayesian Inference for Set-Identified Models"

format:
  revealjs:
    slide-number: true
    show-slide-number: print
    incremental: true
    toc: true
    toc-depth: 1

editor: visual